properties([
    parameters([
        string(name: 'DOCKER_REGISTRY', defaultValue: 'registry.hub.docker.com',                                        description: 'The Docker registry to use'),
        string(name: 'REGISTRY_CREDS',  defaultValue: 'dockerhub',                                                      description: 'The Jenkins credentials ID for the given registry'),
        string(name: 'WEBEX_SPACE_ID',  defaultValue: 'b204c1a0-6862-11e8-9dbc-93ef3cfef186',                           description: 'ID of Webex space to push pass/fail notifications'),
        string(name: 'NAMESPACE',       defaultValue: 'micasnyd',                                                       description: 'The docker namespace to use'),
        string(name: 'IMAGE_NAME',      defaultValue: 'clambc-compiler',                                                description: 'The docker image name to use'),
        string(name: 'REPOSITORY',      defaultValue: 'https://github.com/Cisco-Talos/clamav-bytecode-compiler.git',    description: 'The repository from which to build'),
        string(name: 'BRANCH',          defaultValue: 'rel/0.105',                                                      description: 'The repository branch for this build'),
        string(name: 'FULL_VERSION',    defaultValue: '0.105.1',                                                        description: 'Full version in X.Y.Z format'),
        string(name: 'FEATURE_VERSION', defaultValue: '0.105',                                                          description: 'Feature version in X.Y format'),
        string(name: 'REVISION',        defaultValue: '1',                                                              description: 'Revision of image for tag suffix. Starts at 1'),
        booleanParam(name: 'IS_LATEST', defaultValue: false,                                                            description: 'If "true", will also publish to :latest, and :stable tags.'),
    ]),
    disableConcurrentBuilds(),
    buildDiscarder(logRotator(
        artifactDaysToKeepStr: '10',
        artifactNumToKeepStr: '10',
        daysToKeepStr: '30',
        numToKeepStr: '20'))
])

node('docker-arm64') {
    cleanWs()

    try {
        // Checkout the ClamAV source code
        checkout([
            $class: 'GitSCM', branches: [[name: "${params.BRANCH}"]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [
                [$class: 'RelativeTargetDirectory', relativeTargetDir: '.'],
                [$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true]
            ],
            submoduleCfg: [], userRemoteConfigs: [[url: "${params.REPOSITORY}"]]
        ])

        // Remove the Dockerfile and scripts from the clamav repo, if any.
        sh """
        rm -rf ./Dockerfile
        """

        // Checkout the current repo
        dir(path: 'clamav-docker') {
            checkout scm
        }

        // Use the Dockerfile and scripts from this repo.
        sh """
        cp -r clamav-docker/clamav-bytecode-compiler/unstable/ubuntu/Dockerfile .
        """

        stage('Build Image') {
            withCredentials([usernamePassword(credentialsId: "${params.REGISTRY_CREDS}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWD')]) {
                // Make sure we have the latest base image.
                sh """
                docker pull ubuntu:20.04
                """

                // Login to docker hub
                sh """
                echo "\${_passwd:-\${DOCKER_PASSWD}}" | \
                    docker login --password-stdin --username "${DOCKER_USER}" "${params.DOCKER_REGISTRY}"
                """

                //
                // Build X.Y.Z-R, X.Y.Z, and X.Y tags.
                // And maybe also the 'latest' and 'stable' images.
                //

                // Build X.Y.Z-R image
                sh """
                docker build --tag "${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}" .
                """

                // Publish X.Y.Z-R tag
                sh """
                docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION} ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}
                docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}
                """

                // Publish X.Y.Z tag
                sh """
                docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION} ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}
                docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}
                """

                // Publish X.Y tag
                sh """
                docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION} ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FEATURE_VERSION}
                docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FEATURE_VERSION}
                """

                if (params.IS_LATEST) {
                    // Create & Publish 'stable' and 'latest' tags.
                    sh """
                    docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION} ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:stable
                    docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:stable

                    docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION} ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:latest
                    docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:latest
                    """
                }

                // log-out (again)
                sh """
                docker logout "${docker_registry:-}"
                """
            }
        }

    } catch(err) {
        currentBuild.result = "FAILED"
        sparkSend(
            message: "Docker build of ${params.FULL_VERSION} from ${params.REPOSITORY} branch ${params.BRANCH} for ${params.NAMESPACE}/${params.IMAGE_NAME} [FAILED](${BUILD_URL})",
            spaceList: [[spaceName: "ClamAV Jenkins", spaceId: "${params.WEBEX_SPACE_ID}"]], credentialsId: 'clambuilder', messageType: 'markdown')
        throw err
    }

    sparkSend(
        message: "Docker build of ${params.FULL_VERSION} from ${params.REPOSITORY} branch ${params.BRANCH} for ${params.NAMESPACE}/${params.IMAGE_NAME} [PASSED](${BUILD_URL})",
        spaceList: [[spaceName: "ClamAV Jenkins", spaceId: "${params.WEBEX_SPACE_ID}"]], credentialsId: 'clambuilder', messageType: 'markdown')
}
