properties([
    parameters([
        string(name: 'DOCKER_REGISTRY', description: 'The Docker registry to use'),
        string(name: 'REGISTRY_CREDS',  description: 'The Jenkins credentials ID for the given registry'),
        string(name: 'WEBEX_SPACE_ID',  description: 'ID of Webex space to push pass/fail notifications'),
        string(name: 'FULL_VERSION',    description: 'Full version of ClamAV to build in X.Y.Z format'),
        string(name: 'FEATURE_VERSION', description: "The feature release number in X.Y format"),
        string(name: 'REVISION',        description: 'Revision of image for tag suffix. Starts at 1'),
        string(name: 'REPOSITORY',      description: 'The repository from which to build ClamAV'),
        string(name: 'BRANCH',          description: 'The repository branch for this build'),
        string(name: 'NAMESPACE',       description: 'The docker namespace to use'),
        string(name: 'IMAGE_NAME',      description: 'The docker image name to use'),
        booleanParam(name: 'IS_LATEST', description: 'If "true", will also publish to :latest, and :stable tags.'),
    ]),
    disableConcurrentBuilds(),
    buildDiscarder(logRotator(
        artifactDaysToKeepStr: '10',
        artifactNumToKeepStr: '10',
        daysToKeepStr: '30',
        numToKeepStr: '20'))
])

node('docker-arm64') {
    cleanWs()

    try {
        // Checkout the ClamAV source code
        checkout([
            $class: 'GitSCM', branches: [[name: "${params.BRANCH}"]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [
                [$class: 'RelativeTargetDirectory', relativeTargetDir: '.'],
                [$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true]
            ],
            submoduleCfg: [], userRemoteConfigs: [[url: "${params.REPOSITORY}"]]
        ])

        // Remove the Dockerfile and scripts from the clamav repo, if any.
        sh """
        rm -rf ./Dockerfile ./dockerfiles
        """

        // Checkout the current repo
        dir(path: 'clamav-docker') {
            checkout scm
        }

        // Use the Dockerfile and scripts from this repo.
        sh """
        cp -r clamav-docker/clamav/${params.FEATURE_VERSION}/alpine/Dockerfile clamav-docker/clamav/${params.FEATURE_VERSION}/alpine/scripts .
        """

        stage('Build Image') {
            withCredentials([usernamePassword(credentialsId: "${params.REGISTRY_CREDS}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWD')]) {
                // Make sure we have the latest base image.
                sh """
                docker pull debian:11-slim
                """

                // Login to docker hub
                sh """
                echo "\${_passwd:-\${DOCKER_PASSWD}}" | \
                    docker login --password-stdin --username "${DOCKER_USER}" "${params.DOCKER_REGISTRY}"
                """

                //
                // Build the following images:
                //  - X.Y.Z-R,  X.Y.Z-R_base
                //  - X.Y.Z,    X.Y.Z_base
                //  - X.Y,      X.Y_base
                //
                // And maybe also:
                //  - latest,   latest_base
                //  - stable,   stable_base
                //

                // Build X.Y.Z-R_base image.
                sh """
                docker buildx build --platform linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/ppc64le --tag "${params.IMAGE_NAME}:${params.FULL_VERSION}_base" .
                """

                // Publish X.Y.Z-R_base tag
                sh """
                docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}_base ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}_base
                docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}_base
                """

                // Publish X.Y.Z_base tag
                sh """
                docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}_base ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}_base
                docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}_base
                """

                // Publish X.Y_base tag
                sh """
                docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}_base ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FEATURE_VERSION}_base
                docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FEATURE_VERSION}_base
                """

                if (params.IS_LATEST) {
                    // Create & Publish 'stable_base' and 'latest_base' tags.
                    sh """
                    docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}_base ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:stable_base
                    docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:stable_base

                    docker image tag ${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION}_base ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:latest_base
                    docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:latest_base
                    """
                }

                // The update_db_image.sh script will query for tags during the update process.
                // So give the registry a little time to add the X.Y.Z-R_base image.
                sh """
                sleep 20
                """

                // Pull the X.Y.Z-R_base image, update the DB, and push it out as X.Y.Z-R (without the _base suffix)
                sh """
                DOCKER_REGISTRY="${params.DOCKER_REGISTRY}" \
                CLAMAV_DOCKER_IMAGE="${params.IMAGE_NAME}" \
                CLAMAV_DOCKER_TAG="${params.FULL_VERSION}-${params.REVISION}" \
                    ./scripts/update_db_image.sh -t ${params.FULL_VERSION}-${params.REVISION} -n ${params.NAMESPACE}
                """

                // Login to docker hub again, because the update_db_image.sh script removed our creds in its cleanup stage
                sh """
                echo "\${_passwd:-\${DOCKER_PASSWD}}" | \
                    docker login --password-stdin --username "${DOCKER_USER}" "${params.DOCKER_REGISTRY}"
                """

                // Publish X.Y.Z tag (without the _base suffix)
                sh """
                docker image tag ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION} ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}
                docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}
                """

                // Publish X.Y tag (without the _base suffix)
                sh """
                docker image tag ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION} ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FEATURE_VERSION}
                docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FEATURE_VERSION}
                """

                if (params.IS_LATEST) {
                    // Create & Publish 'stable' and 'latest' tags.
                    sh """
                    docker image tag ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION} ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:stable
                    docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:stable

                    docker image tag ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:${params.FULL_VERSION}-${params.REVISION} ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:latest
                    docker image push ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:latest
                    """
                }

                // log-out (again)
                sh """
                docker logout "${params.DOCKER_REGISTRY}"
                """
            }
        }

    } catch(err) {
        currentBuild.result = "FAILED"
        sparkSend(
            message: "Docker build of ${params.FULL_VERSION} from ${params.REPOSITORY} branch ${params.BRANCH} for ${params.NAMESPACE}/${params.IMAGE_NAME} [FAILED](${BUILD_URL})",
            spaceList: [[spaceName: "ClamAV Jenkins", spaceId: "${params.WEBEX_SPACE_ID}"]], credentialsId: 'clambuilder', messageType: 'markdown')
        throw err
    }

    sparkSend(
        message: "Docker build of ${params.FULL_VERSION} from ${params.REPOSITORY} branch ${params.BRANCH} for ${params.NAMESPACE}/${params.IMAGE_NAME} [PASSED](${BUILD_URL})",
        spaceList: [[spaceName: "ClamAV Jenkins", spaceId: "${params.WEBEX_SPACE_ID}"]], credentialsId: 'clambuilder', messageType: 'markdown')
}
