properties([
    parameters([
        string(name: 'DOCKER_REGISTRY', defaultValue: 'docker.io',                                  description: 'The Docker registry to use'),
        string(name: 'REGISTRY_CREDS',  defaultValue: 'dockerhub',                                  description: 'The Jenkins credentials ID for the given registry'),
        string(name: 'WEBEX_SPACE_ID',  defaultValue: 'b204c1a0-6862-11e8-9dbc-93ef3cfef186',       description: 'ID of Webex space to push pass/fail notifications'),
        string(name: 'NAMESPACE',       defaultValue: 'clamav',                                     description: 'The docker namespace to use'),
        string(name: 'IMAGE_NAME',      defaultValue: 'clamav-debian',                              description: 'The docker image name to use'),
        string(name: 'REPOSITORY',      defaultValue: 'https://github.com/Cisco-Talos/clamav.git',  description: 'The repository from which to build'),
        string(name: 'ECR_PUBLIC_REPO', defaultValue: 'public.ecr.aws/cisco/clamav/clamav',      description: 'ClamAV AWS Public ECR repo'),
        string(name: 'AWS_CREDENTIALS_ID', defaultValue: 'pinkhat-clamav-aws-creds', description: 'Vault path for AWS creds'),
        string(name: 'BASE_IMAGE', defaultValue: 'debian', description: 'Debian base image'),
        string(name: 'BASE_IMAGE_VERSION', defaultValue: '13', description: 'Version for Debian base image'),
        string(name: 'BASE_IMAGE_VARIANT', defaultValue: 'slim', description: 'Variant for Debian base image')

    ]),
    disableConcurrentBuilds(),
    buildDiscarder(logRotator(
        artifactDaysToKeepStr: '10',
        artifactNumToKeepStr: '10',
        daysToKeepStr: '30',
        numToKeepStr: '20'))
])

node('docker-buildx') {
    cleanWs()

    def FULL_BASE_IMAGE = "${params.BASE_IMAGE}:${params.BASE_IMAGE_VERSION}-${params.BASE_IMAGE_VARIANT}"

    try {
        // Checkout the ClamAV source code
        checkout([
            $class: 'GitSCM', branches: [[name: "main"]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [
                [$class: 'RelativeTargetDirectory', relativeTargetDir: '.'],
                [$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true]
            ],
            submoduleCfg: [], userRemoteConfigs: [[url: "${params.REPOSITORY}"]]
        ])

        // Remove the Dockerfile and scripts from the clamav repo, if any.
        sh """
        rm -rf ./Dockerfile ./dockerfiles
        """

        // Checkout the current repo
        dir(path: 'clamav-docker') {
            checkout scm
        }

        // Use the Dockerfile and scripts from this repo.
        sh """
        cp -r clamav-docker/clamav/unstable/debian/Dockerfile* clamav-docker/clamav/unstable/debian/scripts .
        """

        stage('Build Image') {
            withVault([vaultSecrets: [[ path: "clamavbuild-kv/${params.REGISTRY_CREDS}", engineVersion: 1, secretValues:
                        [[envVar: 'DOCKER_USER', vaultKey: 'username'],[envVar: 'DOCKER_PASSWD', vaultKey: 'password']]]]]) {
                // Set docker buildx context
                sh """
                docker buildx use "clamav-test-mul-arch"
                """

                // Make sure we have the latest base image.
                sh """
                docker pull ${FULL_BASE_IMAGE}
                """

                // Login to docker hub
                sh """
                echo "\${_passwd:-\${DOCKER_PASSWD}}" | \
                    docker login --password-stdin --username "${DOCKER_USER}" "${params.DOCKER_REGISTRY}"
                """

                // ClamAV AWS ECR login
                withVault([vaultSecrets: [[ path: "clamavbuild-kv/${params.AWS_CREDENTIALS_ID}", engineVersion: 1, secretValues: [
                    [envVar: 'AWS_ACCESS_KEY_ID', vaultKey: 'aws_access_key_id'],
                    [envVar: 'AWS_SECRET_ACCESS_KEY', vaultKey: 'aws_secret_access_key']
                ]]]]) {

                    sh """
                    aws ecr-public get-login-password --region us-east-1 | \
                    docker login --username AWS --password-stdin public.ecr.aws
                    """
                }

                // Build 'unstable' and 'unstable_base' images.
                sh """
                    docker buildx build --no-cache --platform linux/amd64,linux/arm64,linux/ppc64le \
                        --build-arg BASE_IMAGE=${FULL_BASE_IMAGE} \
                        --sbom=true --provenance mode=max,builder-id=${BUILD_URL} \
                        --annotation org.opencontainers.image.base.name=${FULL_BASE_IMAGE} \
                        --annotation org.cisco.clamav.image.build-number=${BUILD_NUMBER} \
                        --annotation org.opencontainers.image.url=${params.REPOSITORY} \
                        --annotation org.opencontainers.image.source=${params.REPOSITORY} \
                        --annotation org.opencontainers.image.version=${params.FULL_VERSION} \
                        --annotation org.opencontainers.image.ref.name=${params.BRANCH} \
                        --annotation org.opencontainers.image.created="\$(date -Iseconds)" \
                        --tag ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:unstable_base \
                        --tag ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/clamav:unstable_base-${params.BASE_IMAGE} \
                        --tag ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/clamav:unstable_base-${params.BASE_IMAGE}${params.BASE_IMAGE_VERSION}-${params.BASE_IMAGE_VARIANT} \
                        --tag ${params.ECR_PUBLIC_REPO}:unstable_base-${params.BASE_IMAGE} \
                        --tag ${params.ECR_PUBLIC_REPO}:unstable_base-${params.BASE_IMAGE}${params.BASE_IMAGE_VERSION}-${params.BASE_IMAGE_VARIANT} \
                        --rm --push .
                """

                // Sleep so that images are pushed and indexed properly
                sh """
                sleep 20
                """

                // Generate and push an image without the "_base" suffix that contains the databases.
                sh """
                    docker buildx build --no-cache --platform linux/amd64,linux/arm64,linux/ppc64le \
                        --sbom=true --provenance mode=max,builder-id=${BUILD_URL} \
                        --annotation org.opencontainers.image.base.name=${FULL_BASE_IMAGE} \
                        --annotation org.cisco.clamav.image.build-number=${BUILD_NUMBER} \
                        --annotation org.opencontainers.image.url=${params.REPOSITORY} \
                        --annotation org.opencontainers.image.source=${params.REPOSITORY} \
                        --annotation org.opencontainers.image.version=${params.FULL_VERSION} \
                        --annotation org.opencontainers.image.ref.name=${params.BRANCH} \
                        --annotation org.opencontainers.image.created="\$(date -Iseconds)" \
                        --push \
                        --build-arg BASE_IMAGE=${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:unstable_base \
                        --tag ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/${params.IMAGE_NAME}:unstable \
                        --tag ${params.DOCKER_REGISTRY}/${params.NAMESPACE}/clamav:unstable-${params.BASE_IMAGE} \
                        --tag ${params.ECR_PUBLIC_REPO}:unstable-${params.BASE_IMAGE} \
                        --tag ${params.ECR_PUBLIC_REPO}:unstable-${params.BASE_IMAGE}${params.BASE_IMAGE_VERSION}-${params.BASE_IMAGE_VARIANT} \
                        -f Dockerfile.add-db .
                """
            }
        }

    } catch(err) {
        // log-out, if required
        sh """
        docker logout "${params.DOCKER_REGISTRY}" || true
        """

        currentBuild.result = "FAILED"
        sparkSend(
            message: "Docker build from ${params.REPOSITORY} branch main for ${params.NAMESPACE}/${params.IMAGE_NAME} [FAILED](${BUILD_URL})",
            spaceList: [[spaceName: "ClamAV Jenkins", spaceId: "${params.WEBEX_SPACE_ID}"]], credentialsId: 'clambuilder', messageType: 'markdown')
        throw err
    }

    sparkSend(
        message: "Docker build from ${params.REPOSITORY} branch main for ${params.NAMESPACE}/${params.IMAGE_NAME} [PASSED](${BUILD_URL})",
        spaceList: [[spaceName: "ClamAV Jenkins", spaceId: "${params.WEBEX_SPACE_ID}"]], credentialsId: 'clambuilder', messageType: 'markdown')
}
